// <auto-generated />
using System;
using HastaneNobetSistemi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HastaneNobetSistemi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260225062042_SilBastAyarla")]
    partial class SilBastAyarla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HastaneNobetSistemi.Models.Bayram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("BayramAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Bayramlar");
                });

            modelBuilder.Entity("HastaneNobetSistemi.Models.Nobet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NobetTipi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<int>("PuanDegeri")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.ToTable("Nobetler");
                });

            modelBuilder.Entity("HastaneNobetSistemi.Models.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("BayramSira")
                        .HasColumnType("int");

                    b.Property<int>("BuAyBayram")
                        .HasColumnType("int");

                    b.Property<int>("BuAyHaftaIci")
                        .HasColumnType("int");

                    b.Property<int>("BuAyHaftaSonu")
                        .HasColumnType("int");

                    b.Property<int>("HaftaIciSira")
                        .HasColumnType("int");

                    b.Property<int>("HaftaSonuSira")
                        .HasColumnType("int");

                    b.Property<DateTime>("IseGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SonNobetTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("ToplamBayram")
                        .HasColumnType("int");

                    b.Property<int>("ToplamHaftaIci")
                        .HasColumnType("int");

                    b.Property<int>("ToplamHaftaSonu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("HastaneNobetSistemi.Models.Nobet", b =>
                {
                    b.HasOne("HastaneNobetSistemi.Models.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });
#pragma warning restore 612, 618
        }
    }
}
